# ══════════════════════════════════════════════════════════════
#  EUREKASERVER — PROD profile
#  Used in Docker: SPRING_PROFILES_ACTIVE=prod
# ══════════════════════════════════════════════════════════════

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

logging.level.com.lpu=WARN
logging.level.com.netflix.eureka=WARN
logging.level.root=ERROR
