# ══════════════════════════════════════════════════════════════
#  EUREKASERVER — TEST profile
# ══════════════════════════════════════════════════════════════

management.tracing.sampling.probability=0.0

logging.level.com.lpu=INFO
logging.level.com.netflix.eureka=WARN
