# ══════════════════════════════════════════════════════════════
#  APIGATEWAY — TEST profile
# ══════════════════════════════════════════════════════════════

eureka.client.enabled=false
spring.cloud.discovery.enabled=false

management.tracing.sampling.probability=0.0

springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/authservice/v3/api-docs

logging.level.com.lpu=INFO
